version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - CONFIG_PATH
    ports:
      - '7072:7072'

#  caddy:
#    image: alpine
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - $PWD/Caddyfile:/etc/caddy/Caddyfile
