services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/config/values_production.yaml
    ports:
      - "127.0.0.1:7070:7070"
    volumes:
      - $PWD/config:/config
