version: "3.7"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - CONFIG_PATH
    ports:
      - '7070:7070'
    hostname:
      localhost

  caddy:
    image: alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
