services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - CONFIG_PATH
      - TZ=Europe/Moscow
    ports:
      - '7070:7070'

  caddy:
    image: alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
