services:
  caddy:
    image: caddy:2.9.1-alpine
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
#      - ./config/init/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    network_mode: host
