http_server:
  port: 7070
  read_header_timeout: 5s
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

postgres:
  host: localhost
  port: 5433
  dbname: postgres
  user: postgres
  password: postgres